- scripts/output/single/cropland_plots.R
Plots cropland for 2050 and 2100. Can also plot area-diff for all steps and all landuse types.
> updated cropland_plots script with added features

- scripts/output/single/interpolation_cropsplit.R
* change interpolation script to create files for 7 land use types  
(important since gdxAggregagte relying on cell.land_0.5.* to contain our 7 magpie land use types)
* move splitting of crop area into kbe and kfo areas to interpolation_cropsplit.R 
(also contains new names for resulting files 'cell_land_cropsplit_0.5*')  
* default is set to just interpolation (due to memory savings)
> Update interpolation script

- modules/32_forestry/affore_vegc_dec16/equations.gms
Wrong sign on the right-hand side of the equation. Changed the sign from - to +
> bugfix s32_max_aff_area in forestry module

- output.R
- start.R
I replaced srun statements in the code with sbatch --wrap statements as it turned out that the srun-based commands will stay active on the login node for each submitted job until job termination. sbatch --wrap spawns jobs without the need of an active process on the login node.
> switched from srun to sbatch --wrap to avoid process spamming

- config/default.cfg
- core/sets.gms
- modules/35_natveg/dynamic_may18/postsolve.gms
- modules/35_natveg/dynamic_oct19/declarations.gms
- modules/35_natveg/dynamic_oct19/equations.gms
- modules/35_natveg/dynamic_oct19/input.gms
- modules/35_natveg/dynamic_oct19/not_used.txt
- modules/35_natveg/dynamic_oct19/postsolve.gms
- modules/35_natveg/dynamic_oct19/preloop.gms
- modules/35_natveg/dynamic_oct19/presolve.gms
- modules/35_natveg/dynamic_oct19/realization.gms
- modules/35_natveg/dynamic_oct19/scaling.gms
- modules/35_natveg/dynamic_oct19/sets.gms
- modules/35_natveg/module.gms
- scripts/start/ssp1_bugfix.R
In the dynamic_may18 realization age-classes are aggregated for the optimization, and dissagreated in postsolve. However, rounding errors (v35_other.l(j,land35)/pc35_other(j,land35)) can result in infeasiblites.
In the new default dynamic_oct19 realization, this aggression/disagregation is no longer needed.
> added new realization for natveg module to resolve infeasiblites 

- scripts/start/publish_data.R
added start script which allows to publish input files as currently defined in default.cfg on https://rse.pik-potsdam.de/data/magpie/intern to make it accessible to externals
> new start script: publish_data

- modules/10_land/landmatrix_dec18/presolve.gms
- modules/21_trade/off/declarations.gms
- modules/21_trade/off/equations.gms
- modules/21_trade/off/postsolve.gms
- modules/35_natveg/dynamic_oct19/presolve.gms
set kall instead of k in trade "off" realization
boundfix macro on vm_land, v35_secdforest and v35_other to prevent infesabilies in some cases with higher resolution.
> small bugfixes: trade "off" realization + bound fix on vm_land

- CHANGELOG.md
- CITATION.cff
- config/default.cfg
- core/sets.gms
- main.gms
- modules/09_drivers/aug17/sets.gms
- modules/15_food/anthropometrics_jan18/input.gms
- modules/15_food/anthropometrics_jan18/intersolve.gms
- modules/15_food/anthropometrics_jan18/postsolve.gms
- modules/15_food/anthropometrics_jan18/presolve.gms
- modules/15_food/anthropometrics_jan18/sets.gms
- modules/15_food/input/files
- scripts/start/demand_standalone.R
- standalone/demand_model.gms
This is the model code as it has been used for the Food Demand paper. It is based on MAgPIE 4.1 with updates in module "food". 
This version should be released as MAgPIE 4.1.1
> Food Demand Paper version

- modules/55_awms/ipcc2006_aug16/equations.gms
changed to:
"Crop residues in developed regions are fully assigned to house, while in developing regions we assume that 25% of the Nr in residues are consumed directly on croplands during stubble grazing."
> Bugfix bracket bug in confinement equation

- start.R
Bugfix in start.R preventing start.R from trying to use illegal file names for its log files
> bugfix in start.R (avoiding illegal log file names)

- CHANGELOG.md
- modules/35_natveg/dynamic_may20/equations.gms
- modules/35_natveg/dynamic_may20/preloop.gms
- Bugfix v35_secdforest_expansion in 35_other land module.
- gams main.gms for some time steps.
- Notes
> Bugfix v35_secdforest_expansion in 35_other land module.

- .travis.yml
- CHANGELOG.md
- modules/32_forestry/dynamic_may20/declarations.gms
- modules/32_forestry/dynamic_may20/equations.gms
- modules/32_forestry/dynamic_may20/input.gms
- modules/32_forestry/dynamic_may20/preloop.gms
- modules/32_forestry/dynamic_may20/presolve.gms
- modules/32_forestry/input/files
- scripts/start/projects/forestry.R
- ac0 was used instead of ac_est in some case
- minimum carbon treshold for afforesation was overwritten (code moved to end of presolve.gms)
- Removed plantations from vm_cdr_aff because p32_cdr_ac can be changed to plantations with s32_aff_plantation.
- no test runs. No expected impact on performance. Just bugfixes
- GAMS Compilation works fine "gams main.gms action=C"
- Notes
> Bugfixes in 32_forestry

- CHANGELOG.md
- config/default.cfg
- modules/56_ghg_policy/price_jan20/sets.gms
- Added new scenario in f56_emis_policy (maccs_excl_cropland_n2o) that can be chosen when combining climate policy (ghg prices) and fertilizer use efficiency. It avoids double accounting because the MACCS are switched off for all nitrogen-related emissions that are related to cropland (pasture and animal waste management are kept)
- 1.102 = 0.789/0.716  (loss in performance)
- added new scenario description in default.cfg
- Notes
>  Added new scenario in f56_emis_policy (maccs_excl_cropland_n2o) and updated additional data revision

- CHANGELOG.md
- config/default.cfg
- main.gms
- modules/12_interest_rate/input/files
- modules/12_interest_rate/select_apr20/declarations.gms
- modules/12_interest_rate/select_apr20/input.gms
- modules/12_interest_rate/select_apr20/preloop.gms
- modules/35_natveg/dynamic_may20/declarations.gms
- modules/35_natveg/dynamic_may20/input.gms
- modules/35_natveg/dynamic_may20/presolve.gms
- modules/35_natveg/input/files
- bugfix: synchronize HalfEarth scenario with WDPA until 2020, so that scenarios only diverge after 2020
- performance gain = 0.623352/0.6361311 = 0.9799
- like already noted when the HalfEarth Scenario was introduced the first time: runtime is even a bit faster compared to default (WDPA protection)
no additions required 
- [] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).
- Notes: It was only an adjustment when the HalfEarth protection kicks in
> Bugfix in HalfEarth Scenario: Synchronization until 2020 with WDPA protection scenario

- CHANGELOG.md
- core/macros.gms
- core/sets.gms
- bugfix m_fillmissingyears macro. The macro was running over "t" not "t_all". This error-prone. For instance, if t is 2050 and 2100, but data is only availabe until 2095, the macro would use data from 2050 for 2100. Now, the macro runs over t_all, which makes sure that the data from 2095 is used for 2100. 
- No test runs performed
- Notes
> bugfix m_fillmissingyears macro

- CHANGELOG.md
- scripts/output/extra/disaggregation_transitions.R
- added output script for disaggregation of land transitions
- No change of model code. Just output script.
- Notes
> output script for disaggregation of land transitions

- scripts/run_submit/submit_medium.sh
- scripts/run_submit/submit_priority.sh
- scripts/run_submit/submit_priority_maxMem.sh
- scripts/run_submit/submit_short.sh
- scripts/run_submit/submit_short_maxMem.sh
- scripts/run_submit/submit_standby.sh
redirected slurm log from full.log -> slurm.log to avoid write access problems
- Notes
> redirected slurm log from full.log -> slurm.log

- modules/14_yields/managementcalib_aug19/declarations.gms
- modules/14_yields/managementcalib_aug19/preloop.gms
- modules/30_crop/endo_apr21/preloop.gms
- modules/30_crop/endo_jun13/preloop.gms
- scripts/start/extra/lpjml_addon.R
- This is a hotfix for the wrong fm_croparea replacement in the crop modules and wrong proxy yields for the management calib yield realization.
- For croparea:Since sticky realization is based on this values, the current version of sticky does not allocated capital shares correctly. 
- For yields: Proxy yields for regions without historical crop specific areas had wrong proxy yield calculation, that is now fixed.
- Run time has increase quite a lot, so switching on opt file by default is necessary to get a reasonable runtime.
* Current develop branch default : 1.11 h
* This PR's default :  1.32-1.44 h
Some additional info
* Without opt_file + both fixes: runtime > 3h
-> Opt_file is needed
* Without …
> bugfix croparea correction

- scripts/start/extra/lpjml_addon.R
- Update LPjmL and input data version in the lpjml_addon.R script (basically just update default GCM from GFDL to MRI). Since the historical baseline is not different only minor changes in the future trajectories are expected. The change should improve at least a bit the carbon sink estimates (smaller jump) and also enable us to run the baseline GCM for all RCPs.
-> not needed
NA
> Update the lpjml version in addon script

- scripts/start/extra/lpjml_addon.R
- Update lpjml_addon.R settings for sticky from dynamic to free.
* High risk
* This PR's …
> Hf update lpjmladdon

- CHANGELOG.md
- scripts/output/extra/disaggregation.R
- output/extra/disaggregation.R updated to account for country-specific set-aside shares in post-processing
* High risk
* Current …
> country-specific set-aside shares

- config/default.cfg
- modules/32_forestry/dynamic_feb21/input.gms
- modules/32_forestry/dynamic_feb21/preloop.gms
- scripts/output/extra/highres.R
- Removed time dimension from regional maximum afforestation input, which allows users to specify regional afforestation limits.
- This PR is related to this fix in the pik-piam gms R library https://github.com/pik-piam/gms/commit/5fdf9da62d98d41358ed0d75274976048e6fb294
- Without the change in the pik-piam gms R library the construct "$if exist file $include file" was not working in the full.gms file (singleGAMSFile)
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets …
> removed time dimension from regional maximum afforestation input

- config/default.cfg
- modules/34_urban/exo_nov21/presolve.gms
- bugfix: urban land only fixed in 1995, otherwise infeasible in 2000 at higher resolutions
- Change: Discard existing land conversion cost calibration factors by default in case recalibration is needed. This should make the land conversion cost calibration more robust under different model configurations
- No entry in changelog is needed because both changes affect unpublished developments
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in …
> bugfix: urban land

- CHANGELOG.md
- scripts/start_functions.R
This PR removes a misleading warning triggered by check_config when the model is started with an additional repository in place.
* High risk
* Default run based on the current version of the fork from which PR …
> Fixed misleading warning in config check

- config/default.cfg
Update input data to rev4.67, additional data to 4.08 (India changes), and calibration files
* High risk
* Current develop branch …
> Update input to rev4.67

- CHANGELOG.md
- scripts/output/projects/FSEC_dietaryIndicators.R
- scripts/output/projects/FSEC_environmentalPollution_grid.R
- scripts/start/projects/project_FSEC_SWF.R
- Addition of a start script (project_FSEC_SWF.R) and an output script (FSEC_environmentalPollutants_grid.R), with modifications to a third output script (FSEC_dietaryIndicators.R). These scripts are all used in the FSEC project.
NA
> FSEC start script and output scripts

- CHANGELOG.md
- config/default.cfg
- modules/13_tc/endo_jan22/input.gms
- modules/13_tc/endo_jan22/presolve.gms
- modules/13_tc/exo/not_used.txt
Change tech cost upper bound to a config-set GDP share
- This PR changes the tech cost upper bound in the endo TC realization to a permille share ofthe regional GDP (PPP). As the current default is purely technical, this is a necessary constraint for price-driven runs that may push TC and TC cost to extreme heights.
* **Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg**
* Medium risk : Default …
> Add GDP share constraint for tech cost

- CHANGELOG.md
- scripts/output/extra/emulator.R
- scripts/start/extra/emulator.R
- Get rid of dependency to deprecated magpie package, bugfix
NA
> replace magpie with magpie4, bugfix

- config/default.cfg
- modules/44_biodiversity/bii_target/declarations.gms
- modules/44_biodiversity/bii_target/equations.gms
- modules/44_biodiversity/bii_target/input.gms
- modules/44_biodiversity/bii_target/preloop.gms
- modules/44_biodiversity/bii_target/presolve.gms
- Improvment and simplification for setting a lower bound for the BII
* High risk
* Default run from the current develop branch: MAgPIE PR399_SSP2−Ref_updated3
* Default run based on the current version of the fork from which PR is made: MAgPIE …
> Small update in 44_biodiversity

- CHANGELOG.md
- scripts/output/extra/disaggregation_BII.R
- scripts/output/projects/FSDP_collect.R
- scripts/output/rds_report_iso.R
- scripts/start/projects/project_FSEC_Scenarios.R
- scripts/start/projects/project_FSEC_Scenarios_agroecologyTest.R
- The central script for collecting FSDP outputs at regional, iso and grid level is `FSDP_collect.R`
- As soon as other gridded output become available, they should be add to `FSDP_collect.R` in the same way as for BII and land.
- The script also creates plots. For this we need the `[m4fsdp]` R library on the cluster. https://github.com/pik-piam/m4fsdp
- No test runs needed. Just output scripts.
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes …
> Outputs scripts for FSDP runs

- CHANGELOG.md
- scripts/output/projects/FSEC_SimonDietz.R
- scripts/projects/fsec.R
This PR adds an output file, "FSEC_SimonDietz.R" that produces FSEC outputs for SimonDietz. It also updated the population dataset to include all SSPs, rather than only SSP2 and SSP1.
* High risk
* Default run …
> Output script "FSEC_SimonDietz"

- CHANGELOG.md
- scripts/run_submit/submit.R
As explained [here](https://github.com/pik-piam/discussions/discussions/47) magpie runs would complete with exit code 0, even though gams status was not always 2 (locally optimal).
With this PR the first gams status not equal to 2 or 7 is used as exit code. Otherwise if gams status is 7 we use 7 as exit code. In order to avoid confusion with predefined exit codes we add 200 to the exit code, so gams status 6 will result in exit code 206. The exit code is reported in slurm mails, allowing for a quick way to see the gams status of a run.
Sourcing the submit.R script will now quit the R session in order to set the exit code (if there is a problematic gams …
> use gams status as exit code

- CHANGELOG.md
- modules/14_yields/managementcalib_aug19/input.gms
- modules/18_residues/off/realization.gms
- modules/34_urban/exo_nov21/presolve.gms
- modules/34_urban/static/presolve.gms
- modules/52_carbon/normal_dec17/input.gms
- modules/59_som/cellpool_aug16/sets.gms
- modules/59_som/static_jan19/sets.gms
This PR will fix the small soil C mismatches we get from not tracking urban areas within the som module. It will only let ag carbon pools (vegc and litc) be 0 for urban areas, but will use the "other" land soilc values for urban areas. All 59_som realizations will from now on track urban areas (as a noncropland pool together with all other land use types).
For now we manually set fm_carbon_density for soilc in urban within the input.gms file, which will be faded out by end of this year, when all preprocessing will contain meaningful numbers for fm_carbon_density for soilc in urban.  Changes to mrmagpie where already pushed.
-> Made a test run. It run though.
NA
> add urban area to soil C tracking (with natural soil C as proxy)

- CHANGELOG.md
- config/default.cfg
- modules/56_ghg_policy/price_aug22/sets.gms
This PR updates the `additional_data` revision number to **4.32** adding the following new emission policy scenario options to `c56_emis_policy `:
- `ecoSysProtAll`
- `ecoSysProtForest` 
- `ecoSysProtPrimForest` 
- `ecoSysProtOff`
- `ecoSysProtAll_agMgmtExclN2O`
- `ecoSysProtAll_agMgmtExclCH4`
In the first 4 scenarios GHG emission policies related to ecosystem protection are gradually switched off, which in particular also involves exempting all types of GHG emissions from peatlands from the policy in `ecoSysProtForest`, `ecoSysProtPrimForest` and `ecoSysProtOff`. Other N2O and CH4 emissions, i.e those related to agricultural management, are still covered by the policy.
In `ecoSysProtAll_agMgmtExclN2O` all emission related to ecosystem protection are covered by the GHG policy (involving …
> Update additional data revision number adding ecoSysProt scenarios

- scripts/output/projects/FSDP_collect.R
This PR fixes a commonly occurring error that, when one of the scenario's output scripts breaks due to lazy-load errors, the entire FSDP_collect function breaks.
* High risk
* Default run based on the current …
> Bugfix FSDP_collect.R

- scripts/output/projects/FSDP_collect.R
- FSDP output script update
- added bundlesFSDP and validationFSDP
- I made corresponding changes in m4fsdp https://github.com/pik-piam/m4fsdp/blob/master/R/convertReportFSDP.R#L21
- [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards …
> FSDP output script update

- CHANGELOG.md
- config/default.cfg
- changed default value for s56_limit_ch4_n2o_price from 1000 to 4000 for consistency with c57_macc_version = "PBL_2022"
- FSDP runs are feasible
Default run is unchanged.
As expected, there is slightly more non-CO2 emission reduction in climate policy runs the updated version.
- …
> bugfix s56_limit_ch4_n2o_price default value

- config/default.cfg
- modules/56_ghg_policy/price_aug22/sets.gms
This PR updates the `additional_data` revision number to **4.33** adding the following new emission policy scenario option to `c56_emis_policy `
- `ecoSysProtAll_agMgmtOff`
and is an addition to [PR466](https://github.com/magpiemodel/magpie/pull/466).
In `ecoSysProtAll_agMgmtOff` all emissions related to ecosystem protection are covered by the GHG policy (involving all types of GHGs from peatlands). Emissions related to agricultural management (in particular N2O and CH4 emissions, but also other nitrogen-based pollutants and emissions from burning residues) are **exempted** from the GHG policy.
- **Medium risk**: Uncritical changes in the model core (e.g. moderate …
> Update add. data rev. adding ecoSysProtAll_agMgmtOff scenario

- CHANGELOG.md
- config/default.cfg
- config/scenario_config.csv
- config/scenario_fsec.csv
- modules/10_land/input/files
- modules/10_land/landmatrix_dec18/input.gms
- modules/22_land_conservation/area_based_apr22/input.gms
- modules/22_land_conservation/area_based_apr22/preloop.gms
- modules/30_crop/endo_apr21/declarations.gms
- modules/30_crop/endo_apr21/equations.gms
- modules/30_crop/endo_apr21/input.gms
- modules/30_crop/endo_apr21/input/files
- modules/30_crop/endo_apr21/postsolve.gms
- modules/30_crop/endo_apr21/preloop.gms
- modules/30_crop/endo_apr21/presolve.gms
- modules/30_crop/penalty_apr22/declarations.gms
- modules/30_crop/penalty_apr22/equations.gms
- modules/30_crop/penalty_apr22/input.gms
- modules/30_crop/penalty_apr22/input/files
- modules/30_crop/penalty_apr22/postsolve.gms
- modules/30_crop/penalty_apr22/preloop.gms
- modules/30_crop/penalty_apr22/presolve.gms
- modules/30_crop/rotation_apr22/declarations.gms
- modules/30_crop/rotation_apr22/equations.gms
- modules/30_crop/rotation_apr22/input.gms
- modules/30_crop/rotation_apr22/input/files
- modules/30_crop/rotation_apr22/postsolve.gms
- modules/30_crop/rotation_apr22/preloop.gms
- modules/30_crop/rotation_apr22/presolve.gms
- Added an option (`s30_snv_natveg_only`) to the `default.cfg` for deciding whether all non-cropland land types qualify as SNV or only primforest, secdforest and otherland (i.e. 'natveg'). 
- [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and …
> semi-natural vegetation in cropland areas rework

- scripts/output/extra/disaggregation.R
- scripts/output/extra/disaggregation_BII.R
- Bugfix in extra/disaggregation.R …
> bugfix in extra/disaggregation.R

- CHANGELOG.md
- modules/15_food/anthro_iso_jun22/exodietmacro.gms
- modules/62_material/exo_flexreg_apr16/equations.gms
- modules/62_material/exo_flexreg_apr16/preloop.gms
- modules/62_material/exo_flexreg_apr16/realization.gms
- modules/62_material/module.gms
- This PR makes sure that results in case of exo_diet = 1/0 and exo_waste = 1/0 are identical until 2020.
- Bioplastic demand identical in all scenarios until 2020 …
> Bugfix Food and Material module results until 2020

- CHANGELOG.md
- scripts/start_functions.R
fixed bug which could cause compilation errors if the title contains a dot
- Briefly explain the purpose of this pull request
- `scenario_config.csv` has been …
> bugfix for dots in title

- CHANGELOG.md
- config/scenario_fsec.csv
- scripts/projects/fsec.R
This PR updates the FSEC input data tgz. Only the validation data changed, regional and cellular input data stayed the same (checked with `madrat::compareData`). …
> F inputdata fsec

- CHANGELOG.md
- config/default.cfg
- output.R
- scripts/output/extra/highres.R
- scripts/start_functions.R
- HR renvs were missing packages (raster, ncdf4), this PR fixes that
- manually running output.R for multiple runs will now only create lockfile once and copy to each run folder; this should improve performance a lot for these cases
- [`magpie4`](https://github.com/pik-piam/magpie4) R …
> fix renv for HR runs

- CHANGELOG.md
- scripts/calibration/calc_calib.R
- scripts/start/extra/recalibrate.R
- scripts/start/extra/recalibrate_realizations.R
- In this pull request the calc_calib.R was fixed to ensure that the reported calib_factors reported correspond to the divergence of the iteration, and to select the factors, per region, that correspond to the lowest divergence.
- [`magpie4`](https://github.com/pik-piam/magpie4) R library …
> Changes in the best_calib selection criterion

- .Rprofile
- DESCRIPTION
When creating a renv.lock file (via `renv::snapshot`) renv only records versions of packages that "really are dependencies". To determine this renv crawls all R files and reads a file called DESCRIPTION, that's why this PR renames our DEPENDENCIES file to DESCRIPTION.
- …
> DEPENDENCIES -> DESCRIPTION because of renv snapshot logic

- CHANGELOG.md
- modules/31_past/endo_jun13/not_used.txt
- modules/31_past/grasslands_apr22/preloop.gms
- modules/31_past/static/not_used.txt
- Numbers in f31_pastr_suitability.cs3 differ before 2020 for different scenarios, which results in different model outcomes for the historic perid. This PR fixes this problem by setting values to SSP2 defaults before and including 2020.
- **31_past** fixed pasture suitability to SSP2 before and including 2020 (only relevant for grassland implementation)
- The new …
> bugfix pasture suitabilty

- modules/38_factor_costs/sticky_labor/presolve.gms
- This PR fixes slight changes in demand for 2020 between BAU and the capitalSubst scenario (which also caused the differences in the price index) by changing the constraint to be activated only after 2020, not in 2020. From a content-wise logic this shouldn't make a difference, as capital share for 2020 is fixed anyway, but the different formulation of the constraint apparently made the solver find a slightly different solution. 
- **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in …
> fix for divergance in demand in 2020 for capitalSubst scenario

- CHANGELOG.md
- scripts/calibration/calc_calib.R
- In this PR, when a calibration factor has a value equal to the maximum, its divergence is set to the maximum allowed value. Before, it was set to NA, which generated issues. Also, this is done to avoid additional unnecessary iterations.
- [`magpie4`](https://github.com/pik-piam/magpie4) R …
> max calib factor divergence to max divergence

- CHANGELOG.md
- scripts/output/extra/cluster_resolution.R
- scripts/output/extra/land_cluster_shapefile.R
- add cluster_resolution output extra script that writes shapefile with landuse data on cluster resolution to be used as basis for downscaling
- …
> add cluster_resolution output script

- scripts/insertheader/insertheader.R
- scripts/output/extra/disaggregation.R
- scripts/output/extra/disaggregation_LUH2.R
- scripts/output/extra/emulator.R
- scripts/output/projects/inms_reporting_reg.R
- scripts/performance_test.R
- scripts/start/Rprofile.R
- scripts/start_functions.R
- replace `on.exit` with `withr::defer`
on.exit can break `withr` functionality or other `on.exit` calls by always overwriting the function that is executed on exit unless `add=TRUE` is passed, so `withr::defer` is much safer.
This might be the reason why models were not unlocked - the unlock was supposed to happen in an on.exit that was overwritten.
- The new code …
> on.exit -> withr::defer

- CHANGELOG.md
- config/default.cfg
- scripts/npi_ndc/start_npi_ndc.R
This PR contains two components:
1. small fix in CHANGELOG description as we do not follow all rules required to call it semantic versioning, what we are doing.
2. update of the NPI/NDC script so that it can handle now 59k and 67k cells inputs (for that a newer revision of additional_data is required in addition to the changes in the script)
- The new code doesn't …
> Made NPI and NDC calculatiosn ready for 67k cells and removed reference to semantic versioning

- CHANGELOG.md
- scripts/start_functions.R
- During the transition from 59k to 67k clustering there is a parallel structure of clusters with different total number of cells. For this purpose, the way clusters per regions are accounted is flexibilized. magclass::getCPR() is no longer used in start_functions.R. Instead, the information is obtained from a magpie object that contains the full cluster information …
> update start_functions.R such that different cluster sets are possible

- CHANGELOG.md
- config/scenario_config.csv
- config/scenario_fsec.csv
- Cellular input of scenario_config.csv and scenario_fsec.csv was still version 4.85. That caused coupled runs and FSEC runs to fail with the newest develop branch.
- This has now been updated
- Where relevant, put In-code documentation comments
- Properly address updates in …
> Bugfix in scenario config

- output.R
- scripts/start_functions.R
- an error during renv::snapshot was not shown, this PR should fix that
- `scenario_config.csv` has been updated accordingly (important if `default.cfg` has …
> show renv snapshot errors

- CHANGELOG.md
- config/default.cfg
- scripts/output/extra/highres.R
- scripts/start/test_runs.R
- **config** added `cfg$results_folder_highres` which allows to modify the output folder used in the `highres.R` output script
- `scenario_config.csv` has been …
> results folder for highres runs

- CHANGELOG.md
- modules/80_optimization/lp_nlp_apr17/solve.gms
- modules/80_optimization/nlp_apr17/solve.gms
- modules/80_optimization/nlp_par/solve.gms
- modelstat 7 means "Solver terminated early and model was feasible but not yet optimal". In this case, the solprint should be activated to be able to find in which equation the infeasibility occurred
- at modelstat 7, the full solprint is printed now
- Where relevant, put In-code …
> re-introduced solprint when solverstat is 7

- CHANGELOG.md
- modules/30_crop/penalty_apr22/equations.gms
- modules/30_crop/rotation_apr22/equations.gms
- Bugfix: in the non-default realization of 30_crop, rotation_apr22, the fallow land term was on the wrong side of the equation.
- [x ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
- [ x] Self-review own code
- …
>  Bugfix: in the non-default realization of 30_crop, rotation_apr22, the fallow land term was on the wrong side of the equation.

- CHANGELOG.md
- scripts/output/extra/reportMAgPIE2SEALS.R
- Output script for reporting gridded land use patterns to the Spatial Economic Allocation Landscape Simulator (SEALS). …
> New output script for reporting land use to SEALS

- CHANGELOG.md
- DESCRIPTION
This PR fixes two things:
- During the disaggregation of land pools, policies for conserving semi-natural habitat in cropland cells have not been consistently applied.
- Noticeable deviations in the total land sum could occur at times due to mismatches in the calculation of the allocation weights.
The first issue has been fully fixed, while the inaccuracies caused by the allocation weights have been reduced to <0.01 %.
See [here](https://github.com/pik-piam/luscale/commit/bb88a4cd6ceadcde7f9cae56cbaf68edaa321606) for the actual changes.
- **High risk**: Critical …
> fixed disaggregation inaccuracies in luscale

- CHANGELOG.md
- scripts/start_functions.R
(As I never did a MAgPIE PR before, please help me fill out the stuff correctly etc. If my fix is not what you want, please adapt it yourself… I do not even have the right to add reviewers and labels, so please, @dklein-pik and @pfuehrlich-pik, you have to take over)
Running the REMIND-MAgPIE coupled tests prints a warning to the logs:
```
Settings are unknown in provided cfg (cfg$gms$c_input_gdx_path)!
```
This comes from setting cfg$gms$c_input_gdx_path [in start_functions.R](https://github.com/magpiemodel/magpie/blob/09a26cf1881483f9119e4a92f4ee9850a7769050/scripts/start_functions.R#L646) for empty model runs, but not having set this elsewhere. Therefore, I adapted the extras in `check_config` to simply accept that.
- **Low risk**: Simple bugfixes (missing files, updated documentation, …
> Remove unnecessary warning for empty magpie runs

- .zenodo.json
- CITATION.cff
- config/default.cfg
- We identified a critical bug in the rev4.91 inputdata related to proj/6.3.1, this PR switches to rev4.92 where the bug is no longer present
- …
> bugfixed inputdata rev4.92

- CHANGELOG.md
- config/default.cfg
- config/scenario_config.csv
- there is a bug in the rev4.92 inputdata (terra aggregate changed its default behavior wrt na.rm) that was fixed in the presumingly most relevant cases in rev4.93 which this PR sets as default
- scenarios in `scenario_fsec.csv` still use rev4.91, so they should not be used at the moment
- …
> bugfix: inputdata rev4.93

- CHANGELOG.md
- config/default.cfg
- config/scenario_fsec.csv
- modules/14_yields/managementcalib_aug19/input.gms
- modules/14_yields/managementcalib_aug19/preloop.gms
- scripts/start/extra/recalibrate_FSEC.R
Add a switch to turn off the use of yield calibration factors …
> added switch to turn off yield calib

- CHANGELOG.md
- scripts/output/extra/disaggregation.R
- scripts/output/extra/disaggregation_LUH2.R
- Due to set name issues the disaggregation.R and the disaggregation_LUH2.R had to be adjusted to work with the new 'x.y.iso' naming. The fixes are not backward compatible, so most likely this version will not work with 59k input anymore.
- Where relevant, put In-code documentation …
> Fix disaggregation scripts to be used with 67k input

- CHANGELOG.md
- CITATION.cff
- config/default.cfg
- core/sets.gms
- main.gms
- modules/31_past/endo_jun13/not_used.txt
- modules/31_past/grasslands_apr22/input.gms
- modules/31_past/grasslands_apr22/preloop.gms
- modules/31_past/grasslands_apr22/sets.gms
- modules/31_past/input/files
- modules/31_past/static/not_used.txt
- Briefly explain the purpose of this pull request
- Add …
> Bugfix in grasslands_apr22 pasture realization.

- CHANGELOG.md
- scripts/output/extra/reportMAgPIE2SEALS.R
- Due to a change in `magclass::write.magpie` that affected the writing of NetCDF files, some fixes were necessary regarding the reporting of NetCDF files for SEALS
-  …
> changed SEALS reporting and underlying function

- CHANGELOG.md
- config/default.cfg
- modules/21_trade/exo/input.gms
- modules/21_trade/exo/preloop.gms
- **21_trade** v21_manna_from_heaven fixed to zero by default. Without fixing to zero, v21_manna_from_heaven was used unnecessarily in runs started with highres.R in the first time steps, which caused price spikes in the results. 
- [`magpie4`](https://github.com/pik-piam/magpie4) R library …
> bugfix v21_manna_from_heaven highres.R

- CHANGELOG.md
- config/default.cfg
- scripts/output/validation_cell.R
- The purpose of this PR is to add an output script that allows or the validation of magpie outputs, land and crop types, at cellular level.
- …
> Validation cell pdf

- CHANGELOG.md
- modules/34_urban/static/presolve.gms
- **34_urban** `static` realization was not working because `vm_carbon_stock` was referenced without the set `stockType`
- `scenario_config.csv` has been …
> bugfix 34_urban static

- scripts/output/extra/disaggregation_LUH2.R
- replace the only occurance of speed_aggregate in non-deprecated script
- `scenario_config.csv` has been updated accordingly (important if `default.cfg` has …
> replace speed_aggregate

- CHANGELOG.md
- CITATION.cff
- scripts/output/extra/checkSummation.R
added checkSummation output script for consistency checking of report.mif files.
- `scenario_config.csv` has been updated accordingly (important if …
> added summation check

- CHANGELOG.md
- modules/14_yields/managementcalib_aug19/preloop.gms
This PR fixes a division by zero error that occures when using the h16 or h16s5 region mapping using 67k preprocessing. 
The value ```sum((cell(i,j),w), fm_croparea("y1995",j,w,knbe14))``` in LN 130 of the [preloop](https://github.com/magpiemodel/magpie/blob/master/modules/14_yields/managementcalib_aug19/preloop.gms) is above but very close to zero. Like this the >0 condition is fulfilled but still LN 134 results in division by zero. 
- **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic …
> Fix division by zero in yield calibration

- modules/35_natveg/pot_forest_may24/presolve.gms
> bugfix 35_natveg forest recovery

- CHANGELOG.md
- scripts/output/projects/agmip_merge_report.R
- This PR modifies the agmip output script to use the piamInterfaces mapping instead of the deprecated mapping write.reportProject from the iamc package. 
- …
> modified agmip output script to use piaminterfaces

- scripts/output/extra/disaggregation.R
- Bugfix warning disaggregation …
> Bugfix warning disaggregation

- CHANGELOG.md
- output.R
- start.R
bugfix in start.R and output.R …
> bugfix in start.R and output.R

- CHANGELOG.md
- scripts/output/merge_report.R
- scripts/output/rds_report.R
- scripts/output/rds_report_iso.R
- rewrite of merge_report.R based on rds files and rbind, which allows for more flexibility when merging reports
- Avoid inconsistent use of "GLO" instead of "World" in report.rds files.
- [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards …
> update merge_report and rds_report

- scripts/output/rds_report.R
Use 'find' instead of 'ls' to create the list of reportings available in the results archive for shinyresults.
Explanation https://www.baeldung.com/linux/argument-list-too-long-error
> Use 'find' instead of 'ls' to create the list of reportings available for shinyresults

- scripts/run_submit/submit_medium.sh
- scripts/run_submit/submit_priority.sh
- scripts/run_submit/submit_priority_maxMem.sh
- scripts/run_submit/submit_short.sh
- scripts/run_submit/submit_short_maxMem.sh
- scripts/run_submit/submit_standby.sh
- scripts/run_submit/submit_standby_dayMax.sh
- scripts/run_submit/submit_standby_maxMem.sh
- scripts/run_submit/submit_standby_maxMem_dayMax.sh
- scripts/slurmOutput.yml
- scripts/slurmStart.yml
As @dklein-pik pointed out to me: on our new hpc mail-type FAIL needs to be specified to also get a notification mails for failed runs. Providing the additional argument "FAIL" also works on the old cluster. The same was added in remind with https://github.com/remindmodel/remind/pull/1740
- …
> add mail-type FAIL

- CHANGELOG.md
- scripts/start_functions.R
Decide individually for demand and price whether they are read from a REMIND report. Meaning: if a path to a REMIND report is specified for one of the two, read it, regardless of whether a report is also given for the other. Previously, *both* were only read if a path was given for both, or if a path was only given for bioenergy. The new way allows setting demand and price individually, which is required for some standalone scenarios. In the REMIND coupling demand and price will always be read from the same report.
- **High risk**: Critical changes in model core …
> Change the logic used to decide whether bioenergy demand and ghg prices are read from a REMIND report

- CHANGELOG.md
- modules/80_optimization/nlp_apr17/solve.gms
- scripts/start_functions.R
- added missing `require(maglcass)` in start_functions.R
- **80_optimization** abort GAMS in case of execution errors …
> bugfix start_functions.R and 80_optimization

- scripts/run_submit/submit_standby.sh
- scripts/run_submit/submit_standby_dayMax.sh
- scripts/run_submit/submit_standby_maxMem.sh
- scripts/run_submit/submit_standby_maxMem_dayMax.sh
- scripts/slurmOutput.yml
- scripts/slurmStart.yml
The standby qos has been moved to the priority partition:
```
scontrol show partition
PartitionName=standard
AllowGroups=ALL AllowAccounts=ALL AllowQos=short,medium,long
AllocNodes=ALL Default=YES QoS=N/A
DefaultTime=NONE DisableRootJobs=NO ExclusiveUser=NO GraceTime=0 Hidden=NO
MaxNodes=UNLIMITED MaxTime=UNLIMITED MinNodes=0 LLN=NO MaxCPUsPerNode=UNLIMITED
Nodes=csl14c[177-180],csm14c[181-240],csn14c[121-176],cso14c[61-120]
PriorityJobFactor=1 PriorityTier=1 RootOnly=NO ReqResv=NO OverSubscribe=NO
OverTimeLimit=NONE PreemptMode=OFF
State=UP TotalCPUs=23040 TotalNodes=180 SelectTypeParameters=NONE
JobDefaults=(null)
DefMemPerNode=UNLIMITED MaxMemPerNode=UNLIMITED
TRES=cpu=23040,mem=121320000M,node=180,billing=23040
PartitionName=priority
AllowGroups=ALL AllowAccounts=ALL …
```
> modify standby runs to include partition information

- scripts/run_submit/submit_priority.sh
- scripts/run_submit/submit_priority_maxMem.sh
- scripts/run_submit/submit_standby.sh
- scripts/run_submit/submit_standby_dayMax.sh
- scripts/run_submit/submit_standby_maxMem.sh
- scripts/run_submit/submit_standby_maxMem_dayMax.sh
- scripts/slurmOutput.yml
- scripts/slurmStart.yml
Remove the added --partition= lines from the job submission scripts now cluster can automatically choose the correct partition if this information is not included. …
> remove partition information from job submission scripts

- CHANGELOG.md
- scripts/output/extra/convertToNetCDF.R
This output script converts all grid-level .mz files to netCDF files. It selects the files based on their ending with either 0.5.mz or 0.5_share.mz.
- …
> Added convertToNetCDF output script

- CHANGELOG.md
- config/default.cfg
- In this PR the default realization for the 38_factor_costs module was switched to `sticky_feb18`. Regional dynamics are similar to the per_ton_fao_may22 (previous default realization). However, sticky_feb18's land-use high-resolution outputs better fit historical and initialization values. …
> Shift to sticky as default realization in the 38_factor_costs module

- CHANGELOG.md
- DESCRIPTION
- config/default.cfg
- config/projects/scenario_config_year_fix.csv
- scripts/output/extra/disaggregation.R
- scripts/output/extra/highres.R
- scripts/output/extra/runSEALSallocation.R
- scripts/projects/fsec.R
- scripts/run_submit/submit_priority.sh
- scripts/run_submit/submit_priority_highMem.sh
- scripts/run_submit/submit_short.sh
- scripts/run_submit/submit_short_highMem.sh
- scripts/run_submit/submit_standby.sh
- scripts/run_submit/submit_standby_dayMax.sh
- scripts/run_submit/submit_standby_highMem.sh
- scripts/run_submit/submit_standby_highMem_dayMax.sh
- scripts/slurmOutput.yml
- scripts/start/projects/GENIE_0_default.R
- scripts/start/projects/GENIE_1_tau-export.R
- scripts/start/projects/GENIE_2_bm-priced.R
- scripts/start/projects/GENIE_3_bm-demand.R
- scripts/start/projects/GENIE_4_feedback.R
- scripts/start/projects/paper_healthyLscps.R
- scripts/start/projects/paper_peatlandTax.R
- scripts/start/projects/project_ABCDR.R
- scripts/start/projects/project_EAT2p0.R
- scripts/start/projects/project_EAT2p0_DeepDive.R
- scripts/start/projects/project_LAMACLIMA_WP4.R
- Added start script for 'healthy landscapes paper'
- Added script for automatic submission of SEALS allocation runs
- `.nc` files are no longer exported by default after disaggregation of MAgPIE outputs
- updated `magpie4` dependency to `2.12.0` to [adjust lowpass filter based on sm_fix_SSP2 in emisCO2](https://github.com/pik-piam/magpie4/commit/2bfb4ccb4ebfb371e1944fccc20b67417d663b37)
- This PR should go into the next release 4.8.2 @pascal-sauer 
- **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a …
> Start script 'healthy landscapes paper' and output script for automatic submission of SEALS runs

- .Rprofile
- DESCRIPTION
- Makefile
- renv/activate.R
- scripts/output/extra/convertToNetCDF.R
- this PR makes magpie compatible with renv 1.0.8, by requiring a newer piamenv version
- essentially with renv 1.0.8 `type = getOption("pkgType")` needs to be set explicitly, even though it should be default when calling e.g. renv::install or renv::update
- …
> upgrade renv to 1.0.8

- Makefile
- renv/activate.R
- use renv 1.0.9 which is a hotfixed version of 1.0.8 which does not require setting the type arg explicitly, especially this means interactive `renv::install` and `renv::update` calls just work again
- [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly …
> upgrade to renv 1.0.9

- CHANGELOG.md
- scripts/start/extra/emulator.R
- scripts/start_functions.R
- REMIND reports in US$2017 now, so MAgPIE only finds those data if it searches for US$2017. That also fits to [these lines](https://github.com/magpiemodel/magpie/blob/8ef5c646587bbea38b48357a541a6bfa8f1c897f/modules/56_ghg_policy/price_aug22/input.gms#L108-L112) where the data is expected in `USD17MER per t`.
- The new code doesn't contain declared but unused …
> Adjust US$2005 -> 2017 for data read from REMIND

- CHANGELOG.md
- config/default.cfg
- modules/62_material/exo_flexreg_apr16/input.gms
- modules/62_material/exo_flexreg_apr16/preloop.gms
- modules/62_material/exo_flexreg_apr16/presolve.gms
This PR adds a switch to turn off future bioplastic demand (instead of keeping it constant at 2020 values or increasing demand to an exogenously set target). This option is necessary, as both `begr` and `betr` are used as biomass for bioplastics, which is in conflict with `c30_bioen_type` set to `begr` or `betr` only (fixing the production of the respective other to zero).
- No hard coded numbers and cluster/country/region …
> switch to turn off future bioplastic demand

- CHANGELOG.md
- modules/29_cropland/detail_apr24/presolve.gms
- scripts/start/projects/project_ABCDR.R
- **29_cropland** treecover age-class growth was not working properly because ac_sub was erroneously not fixed  …
> bugfix tree cover on cropland

- scripts/output/extra/highres.R
- improved check if regional AR exceeds global AR limit
- Add …
> bugfix warning in highres output script

- scripts/output/rds_report.R
- scripts/output/rds_report_iso.R
With the most up-to-date R packages, units in `report.rds` are missing. 
Therefore, results don't show up in `shinyresults::appResults()`
I guess the problem comes from `as.quitte(report)` and might be related to the use $ signs in our reporting.
The file `report.mif` seems fine. 
Reading this file again after writing solves the problem. 
I'm sure that there is a better solution than this hotfix but we need to be able to look at our results.
@pascal-sauer It would be great if you could have a look into this.
- **High risk**: Critical changes in model core or …
> hotfix for rds_report.R output script: fix units in "report.rds" file

- scripts/output/rds_report.R
With this PR we get a warning if the regex used in as.quitte does not match a variable. This should prevent the shiny missing unit issue in the future.
- …
> check variable + unit format in rds_report

- scripts/downloader/inputdelete.cfg
- scripts/start/test_runs.R
- FSEC AMTs one folder per scenario, instead of an additional one each week with timestamp (what we currently have)
- delete existing spamplots when downloading new data so they don't accumulate (esp. relevant for AMT folder)
- [`magpie4`](https://github.com/pik-piam/magpie4) R library has …
> FSEC AMTs one folder per scenario, inputdelete spamplots

- CHANGELOG.md
- config/default.cfg
- scripts/output/extra/runSEALSallocation.R
- Reworked `extra/runSEALSallocation.R` so that peatland rewetting is automatically considered during a SEALS allocation run.
- additional data >4.60 includes a SEALS model coefficients file that is modified depending on the scenario settings.
- …
> Peatland rewetting automatically considered during SEALS downscaling

- scripts/start/projects/paper_MitiConsv.R
- There appeared to be an unexpected cropland trajectory due to issues in the NPI scenario in coupled runs. Also, the yield calibration led to strange behaviour. This PR takes care of this in the start script.
- [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated …
> calibration and coupled NPI fixes in MitiConsv start script

- CHANGELOG.md
- DESCRIPTION
- README.md
- config/default.cfg
- config/projects/scenario_config_fsec.csv
- main.gms
- scripts/calibration/landconversion_cost.R
- scripts/start/extra/recalibrateH16.R
- scripts/start/extra/recalibrate_FSEC.R
- scripts/start/extra/recalibrate_default.R
- scripts/start/projects/project_ABCDR.R
- scripts/start_functions.R
- **scripts** land conversion cost calibration for cropland - FAO as target data set instead of MAgPIEown
- **default.cfg** settings for  land conversion cost calibration updated
The file `f39_calib.csv` now includes meta information on the settings used for generating the calibration factors:
- The new code doesn't contain declared but unused parameters or …
> Update land conversion cost calibration for cropland - FAO as target data set

- CHANGELOG.md
- config/default.cfg
- scripts/output/extra/runSEALSallocation.R
- The constraint to maintain 20% semi-natural vegetation at the 1x1km scale is passed on to SEALS
- `scenario_config.csv` has been updated accordingly …
> Added SNV20 constraint to SEALS coupling script

- CHANGELOG.md
- DESCRIPTION
- config/default.cfg
- core/macros.gms
- modules/21_trade/selfsuff_reduced/input.gms
- modules/21_trade/selfsuff_reduced_bilateral22/input.gms
- modules/32_forestry/dynamic_may24/input.gms
- modules/32_forestry/dynamic_may24/presolve.gms
- scripts/start/projects/project_ScenarioMIP.R
In the current develop, we observe huge negative prices for wood in CHA in 2070, and huge costs for trade in 2070 in other regions. The reason for this is that we enfore harvest of timber plantations at rotation age. In the specific case above, this creates a conflict with equation `q21_trade_reg_up`. Put simply, enforced wood production from timber plantations is higher than allowed by `q21_trade_reg_up`, which results in negative prices. 
This PR resolves this issues by allowing for more flexibility in harvest from timber plantations. Timber plantation harvest is no longer enforced at rotation age to avoid conflicts with `q21_trade_reg_up.
In addition, cost for additional imports to maintain feasibility are reduced from 12300 to 1500 USD17MER per tDM to avoid implausibly high costs and …
> Bugfix forestry prices and trade cost

- modules/09_drivers/aug17/input.gms
- fix a missing s that shortly confused me and harmonize format
- `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been …
> fix typo in 09_drivers/aug17/input.gms

- CHANGELOG.md
- config/default.cfg
- modules/39_landconversion/calib/input.gms
- scripts/output/extra/disaggregation_LUH2.R
Replace common spelling error "foresty" with the correct "forestry". No functional change.
> Foresty -> Forestry

- CHANGELOG.md
- DESCRIPTION
- scripts/output/extra/disaggregation.R
- .dissagLandConsv was moved to magpie4::disaggregateLandConservation, see https://github.com/pik-piam/magpie4/pull/82 …
> use magpie4::disaggregateLandConservation

- CHANGELOG.md
- DESCRIPTION
- config/default.cfg
- config/scenario_config.csv
- modules/56_ghg_policy/price_aug22/declarations.gms
- modules/56_ghg_policy/price_aug22/equations.gms
- modules/56_ghg_policy/price_aug22/input.gms
- modules/56_ghg_policy/price_aug22/preloop.gms
- scripts/start/projects/project_ScenarioMIP.R
- scripts/start/projects/project_WetHorizons.R
- **56_ghg_policy** added optional temporal fader for start of C prive driven afforestation
- **scenario_config** update of VLLO scenario to EAT-Lancet 2
- updated start scripts for ScenarioMIP and WetHorizons
- [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated …
> optional temporal fader for start of C prive driven afforestation

- config/default.cfg
This PR fixes an accidental change to the scenario of the cellular input data (wrong ssp370, corrected ssp245). …
> Changes default cellular input data back to ssp245

- CHANGELOG.md
- modules/14_yields/managementcalib_aug19/preloop.gms
- bugfix 14_yield: avoid division by zero for special cases
- …
> bugfix 14_yield avoid division by zero for special cases
